# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/crazy/Documents/TestUI/roboanimator.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RoboAnimator(object):
    def setupUi(self, RoboAnimator):
        RoboAnimator.setObjectName("RoboAnimator")
        RoboAnimator.resize(1610, 891)
        RoboAnimator.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(RoboAnimator)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.anims = QtWidgets.QWidget()
        self.anims.setObjectName("anims")
        self.animLayout = QtWidgets.QVBoxLayout(self.anims)
        self.animLayout.setContentsMargins(11, 11, 11, 11)
        self.animLayout.setSpacing(6)
        self.animLayout.setObjectName("animLayout")
        self.tabWidget_2.addTab(self.anims, "")
        self.motors = QtWidgets.QWidget()
        self.motors.setObjectName("motors")
        self.motorLayout = QtWidgets.QVBoxLayout(self.motors)
        self.motorLayout.setContentsMargins(11, 11, 11, 11)
        self.motorLayout.setSpacing(6)
        self.motorLayout.setObjectName("motorLayout")
        self.tabWidget_2.addTab(self.motors, "")
        self.accs = QtWidgets.QWidget()
        self.accs.setObjectName("accs")
        self.accessoriesLayout = QtWidgets.QVBoxLayout(self.accs)
        self.accessoriesLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.accessoriesLayout.setContentsMargins(11, 11, 11, 11)
        self.accessoriesLayout.setSpacing(6)
        self.accessoriesLayout.setObjectName("accessoriesLayout")
        self.tabWidget_2.addTab(self.accs, "")
        self.out = QtWidgets.QWidget()
        self.out.setObjectName("out")
        self.outputLayout = QtWidgets.QVBoxLayout(self.out)
        self.outputLayout.setContentsMargins(11, 11, 11, 11)
        self.outputLayout.setSpacing(6)
        self.outputLayout.setObjectName("outputLayout")
        self.tabWidget_2.addTab(self.out, "")
        self.horizontalLayout.addWidget(self.tabWidget_2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(335, 754))
        self.scrollArea.setMaximumSize(QtCore.QSize(335, 754))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 333, 752))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        RoboAnimator.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(RoboAnimator)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1610, 47))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuRun = QtWidgets.QMenu(self.menuBar)
        self.menuRun.setObjectName("menuRun")
        self.menuDebug = QtWidgets.QMenu(self.menuBar)
        self.menuDebug.setObjectName("menuDebug")
        RoboAnimator.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(RoboAnimator)
        self.statusBar.setObjectName("statusBar")
        RoboAnimator.setStatusBar(self.statusBar)
        self.actionImport_Animation = QtWidgets.QAction(RoboAnimator)
        self.actionImport_Animation.setObjectName("actionImport_Animation")
        self.actionConnect_Port = QtWidgets.QAction(RoboAnimator)
        self.actionConnect_Port.setObjectName("actionConnect_Port")
        self.actionImportAnimationData = QtWidgets.QAction(RoboAnimator)
        self.actionImportAnimationData.setObjectName("actionImportAnimationData")
        self.actionWriteData = QtWidgets.QAction(RoboAnimator)
        self.actionWriteData.setObjectName("actionWriteData")
        self.actionTest_Run = QtWidgets.QAction(RoboAnimator)
        self.actionTest_Run.setObjectName("actionTest_Run")
        self.actionRevert = QtWidgets.QAction(RoboAnimator)
        self.actionRevert.setObjectName("actionRevert")
        self.actionEdit_Animation = QtWidgets.QAction(RoboAnimator)
        self.actionEdit_Animation.setObjectName("actionEdit_Animation")
        self.actionImport_Animation_2 = QtWidgets.QAction(RoboAnimator)
        self.actionImport_Animation_2.setObjectName("actionImport_Animation_2")
        self.actionsetAppPath = QtWidgets.QAction(RoboAnimator)
        self.actionsetAppPath.setObjectName("actionsetAppPath")
        self.actionsetBlenderPath = QtWidgets.QAction(RoboAnimator)
        self.actionsetBlenderPath.setObjectName("actionsetBlenderPath")
        self.actionImport_Robot_Data = QtWidgets.QAction(RoboAnimator)
        self.actionImport_Robot_Data.setObjectName("actionImport_Robot_Data")
        self.menuFile.addAction(self.actionImport_Animation)
        self.menuFile.addAction(self.actionConnect_Port)
        self.menuFile.addAction(self.actionImportAnimationData)
        self.menuFile.addAction(self.actionWriteData)
        self.menuFile.addAction(self.actionImport_Robot_Data)
        self.menuEdit.addAction(self.actionEdit_Animation)
        self.menuEdit.addAction(self.actionRevert)
        self.menuRun.addAction(self.actionTest_Run)
        self.menuDebug.addAction(self.actionsetAppPath)
        self.menuDebug.addAction(self.actionsetBlenderPath)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuDebug.menuAction())

        self.retranslateUi(RoboAnimator)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RoboAnimator)

    def retranslateUi(self, RoboAnimator):
        _translate = QtCore.QCoreApplication.translate
        RoboAnimator.setWindowTitle(_translate("RoboAnimator", "RoboAnimator"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.anims), _translate("RoboAnimator", "Animation"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.motors), _translate("RoboAnimator", "Robot IO"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.accs), _translate("RoboAnimator", "Sounds"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.out), _translate("RoboAnimator", "Output"))
        self.menuFile.setTitle(_translate("RoboAnimator", "File"))
        self.menuEdit.setTitle(_translate("RoboAnimator", "Edit"))
        self.menuRun.setTitle(_translate("RoboAnimator", "Run"))
        self.menuDebug.setTitle(_translate("RoboAnimator", "Debug"))
        self.actionImport_Animation.setText(_translate("RoboAnimator", "Import Animation"))
        self.actionConnect_Port.setText(_translate("RoboAnimator", "Connect Port"))
        self.actionImportAnimationData.setText(_translate("RoboAnimator", "Import Animation Data"))
        self.actionWriteData.setText(_translate("RoboAnimator", "Write Data"))
        self.actionTest_Run.setText(_translate("RoboAnimator", "Test Run"))
        self.actionRevert.setText(_translate("RoboAnimator", "Revert"))
        self.actionEdit_Animation.setText(_translate("RoboAnimator", "Edit Animation"))
        self.actionImport_Animation_2.setText(_translate("RoboAnimator", "Import Animation"))
        self.actionsetAppPath.setText(_translate("RoboAnimator", "setAppPath"))
        self.actionsetBlenderPath.setText(_translate("RoboAnimator", "setBlenderPath"))
        self.actionImport_Robot_Data.setText(_translate("RoboAnimator", "Import Robot Data"))

